---
title: "Using `posterior_predict` with varying output values"
author: "brms team"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: yes
vignette: >
  %\VignetteIndexEntry{Using `posterior_predict` with varying output values}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
params:
  EVAL: !r identical(Sys.getenv("NOT_CRAN"), "true")
---

```{r, SETTINGS-knitr, include=FALSE}
stopifnot(require(knitr))
options(width = 90)
knit_hooks$set(pngquant = knitr::hook_pngquant)
opts_chunk$set(
  comment = NA,
  message = FALSE,
  warning = FALSE,
  eval = if (isTRUE(exists("params"))) params$EVAL else FALSE,
  dev = "ragg_png",
  dpi = 72,
  fig.retina = 1.5,
  fig.asp = 0.8,
  fig.width = 5,
  out.width = "60%",
  fig.align = "center",
  pngquant = "--speed=1 --quality=50"
)
library(ggplot2)
devtools::load_all()
library(extraDistr)
theme_set(theme_default())

n <- 200
```

## Binomial model
### Calibrated

```{r binom1-fit, include = FALSE}
set.seed(42)
beta0 <- -1
beta1 <- 0.8

dat_binom <- data.frame(x = rnorm(n))
dat_binom$size <- sample(10:30, n, replace = TRUE)
dat_binom$y <- rbinom(n, size = dat_binom$size,
  prob = plogis(beta0 + beta1 * dat_binom$x))

fit_binom_calibrated <- brms::brm(
  formula = "y | trials(size) ~ x",
  data    = dat_binom,
  family  = binomial(link = "logit"),
  chains  = 2,
  seed    = 42
)
```

```{r binom1-dens}
bayesplot::ppc_bars(
  y = dat_binom$y,
  yrep = posterior_predict(fit_binom_calibrated)
)
```

```{r binom1-ecdf-random}
pits <- posterior_predict(
  fit_binom_calibrated,
  output = "probability"
)
bayesplot::ppc_pit_ecdf(pit = colMeans(pits)) +
  labs(title = "Binomial model with standard CDF")
```

```{r binom1-ecdf}
pits <- posterior_predict(
  fit_binom_calibrated,
  output = "pit"
)
bayesplot::ppc_pit_ecdf(pit = colMeans(pits)) +
  labs(title = "Binomial model with randomized PIT")
```

### Miscalibrated
```{r binom2-fit, include=FALSE}
phi <- 2
alpha <- phi * 0.3
beta <- phi * (1 - 0.3)

dat_overdisp <- data.frame(x = rnorm(n))
dat_overdisp$size <- sample(10:30, n, replace = TRUE)
dat_overdisp$y <- rbbinom(n, size = dat_overdisp$size, alpha = alpha,
  beta = beta)

fit_binom_miscalibrated <- brms::brm(
  formula = "y | trials(size) ~ x",
  data = dat_overdisp,
  family = binomial(link = "logit"),
  chains = 2,
  seed = 42
)
```

```{r binom2-dens}
bayesplot::ppc_bars(
  y = dat_overdisp$y,
  yrep = posterior_predict(fit_binom_miscalibrated)
)
```

```{r binom2-ecdf-random}
pits <- posterior_predict(
  fit_binom_miscalibrated,
  output = "probability"
)
bayesplot::ppc_pit_ecdf(pit = colMeans(pits)) +
  labs(title = "Binomial model with standard CDF \n(miscalibrated)")
```

```{r binom2-ecdf}
pits <- posterior_predict(
  fit_binom_miscalibrated,
  output = "pit"
)
bayesplot::ppc_pit_ecdf(pit = colMeans(pits)) +
  labs(title = "Binomial model with randomized PIT \n(miscalibrated)")
```

## Beta-Binomial

```{r betabinom, include = FALSE}
set.seed(42)
beta0 <- -1
beta1 <- 0.8
phi   <- 5   # overdispersion parameter (smaller = more overdispersed)

dat_bb <- data.frame(x = rnorm(n))
dat_bb$size <- sample(10:30, n, replace = TRUE)

# Simulate from beta-binomial: draw p from Beta, then y | p ~ Binomial
mu    <- plogis(beta0 + beta1 * dat_bb$x)   # mean probability
alpha <- mu * phi
beta  <- (1 - mu) * phi
p_i   <- rbeta(n, shape1 = alpha, shape2 = beta)
dat_bb$y <- rbinom(n, size = dat_bb$size, prob = p_i)

fit_bb_calibrated <- brms::brm(
  formula = y | trials(size) ~ x,
  data    = dat_bb,
  family  = beta_binomial(link = "logit"),
  chains  = 2,
  seed    = 42
)
```

```{r betabinom-dens}
bayesplot::ppc_bars(
  y = dat_bb$y,
  yrep = posterior_predict(fit_bb_calibrated)
)
```

```{r betabinom-ecdf-random}
pits <- posterior_predict(fit_bb_calibrated, output = "pit")

bayesplot::ppc_pit_ecdf(pit = colMeans(pits)) +
  labs(title = "Beta-Binomial model with randomized PIT")
```

## Negative Binomial
### Parameterization with mu and shape

```{r negbinom1, include = FALSE}
beta0 <- 0.5
beta1 <- 0.8
phi   <- 3

dat_nb_shape <- data.frame(x = rnorm(n))
dat_nb_shape$y <- rnbinom(n,
  mu   = exp(beta0 + beta1 * dat_nb_shape$x),
  size = phi
)

fit_nb_shape <- brm(
  formula = y ~ x,
  data    = dat_nb_shape,
  family  = negbinomial(link = "log"),
  chains  = 2,
  seed    = 42
)
```

```{r negbinom1-dens}
bayesplot::ppc_bars(
  y = dat_nb_shape$y,
  yrep = posterior_predict(fit_nb_shape)
)
```

```{r negbinom1-ecdf-random}
pits <- posterior_predict(fit_nb_shape, output = "pit")

bayesplot::ppc_pit_ecdf(pit = colMeans(pits)) +
  labs(title = "Negative-Binomial model with randomized PIT \n (mu, shape parameterization)")
```

###  Parameterization with mu and sigma

```{r negbinom2, include = FALSE}
beta0 <- 0.5
beta1 <- 0.8
sigma <- 0.5

dat_nb_sigma <- data.frame(x = rnorm(n))
dat_nb_sigma$y <- rnbinom(n,
  mu   = exp(beta0 + beta1 * dat_nb_sigma$x),
  size = 1 / sigma
)

fit_nb_sigma <- brm(
  formula = y ~ x,
  data    = dat_nb_sigma,
  family  = negbinomial2(link = "log"),
  chains  = 2,
  seed    = 42
)
```

```{r negbinom2-dens}
bayesplot::ppc_bars(
  y = dat_nb_sigma$y,
  yrep = posterior_predict(fit_nb_sigma)
)
```

```{r negbinom2-ecdf-random}
pits <- posterior_predict(fit_nb_sigma, output = "pit")

bayesplot::ppc_pit_ecdf(pit = colMeans(pits)) +
  labs(title = "Negative-Binomial model with randomized PIT \n (mu, sigma parameterization)")
```

## Poisson

```{r pois-fit, include = FALSE}
beta0 <- 0.5
beta1 <- 0.8

dat_pois <- data.frame(x = rnorm(n))
dat_pois$y <- rpois(n, lambda = exp(beta0 + beta1 * dat_pois$x))

fit_pois <- brm(
  formula = "y ~ x",
  data    = dat_pois,
  family  = poisson(link = "log"),
  chains  = 2,
  seed    = 42
)
```

```{r pois-dens}
bayesplot::ppc_bars(
  y = dat_pois$y,
  yrep = posterior_predict(fit_pois)
)
```

```{r pois-ecdf-random}
pits <- posterior_predict(fit_pois, output = "pit")

bayesplot::ppc_pit_ecdf(pit = colMeans(pits)) +
  labs(title = "Poisson model with randomized PIT")
```

```{r pois-ecdf}
pits <- posterior_predict(fit_pois, output = "probability")

bayesplot::ppc_pit_ecdf(pit = colMeans(pits)) +
  labs(title = "Poisson model with standard CDF")
```

## Normal

```{r norm-fit, include = FALSE}
dat_normal <- data.frame(
  y = rnorm(n, mean = 1.0, sd = 0.8)
)

fit_norm <- brm(
  formula = "y ~ 1",
  data = dat_normal,
  family = gaussian(),
  chains = 2,
  seed = 42
)
```

```{r norm-dens}
bayesplot::ppc_dens_overlay(
  y = dat_normal$y,
  yrep = posterior_predict(fit_norm)
)
```

```{r norm-ecdf-probability}
pits <- posterior_predict(fit_norm, output = "probability")
bayesplot::ppc_pit_ecdf(pit = colMeans(pits))
```

```{r norm-ecdf-pit}
pits <- posterior_predict(fit_norm, output = "pit")
bayesplot::ppc_pit_ecdf(pit = colMeans(pits))
```

## Student-t

```{r t-fit, include = FALSE}
dat_student <- data.frame(
  y = rt(n, df = 5)
)

fit_student <- brm(
  formula = "y ~ 1",
  data = dat_student,
  family = student(),
  chains = 2,
  seed = 42
)
```

```{r t-dens}
bayesplot::ppc_dens_overlay(
  y = dat_student$y,
  yrep = posterior_predict(fit_student)
)
```

```{r t-ecdf}
pits <- posterior_predict(fit_student, output = "probability")
bayesplot::ppc_pit_ecdf(pit = colMeans(pits))
```
