---
title: "A list of blog posts about brms"
author: "Paul Bürkner"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: yes
params:
  EVAL: !r identical(Sys.getenv("NOT_CRAN"), "true")
---

<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{A list of blog posts about brms}
%\VignetteEncoding{UTF-8}
-->

Several people have blogged about **brms** and this vignette is intended to provide links to those blog posts.

## List of blog posts

- [Mixed effects models: Is it time to go Bayesian by default?](http://babieslearninglanguage.blogspot.de/2018/02/mixed-effects-models-is-it-time-to-go.html) by Michael Frank
- [Statistical Rethinking with brms, ggplot2, and the tidyverse](https://osf.io/97t6w/) by Solomon Kurz
- [Easily made fitted and predicted values made easy](http://thestudyofthehousehold.com/post/easily-made-fitted-and-predicted-values-made-easy/) by Andrew MacDonald
- [How to compute Bayes factors using lm, lmer, BayesFactor, brms, and JAGS/stan/pymc3](https://rpubs.com/lindeloev/bayes_factors) by Jonas Kristoffer Lindelov
- [Confounded dose-response effects of treatment adherence: fitting Bayesian instrumental variable models using brms](http://rpsychologist.com/adherence-analysis-IV-brms) by Kristoffer Magnusson
- [PK/PD reserving models](https://magesblog.com/post/2018-01-30-pkpd-reserving-models/) by Markus Gesmann
- [Hierarchical compartmental reserving models ](https://magesblog.com/post/hierarchical-compartmental-reserving-models/) by Markus Gesmann
- [Diffusion/Wiener Model Analysis with brms – Part II: Model Diagnostics and Model Fit](http://singmann.org/wiener-model-analysis-with-brms-part-ii/) by Henrik Singmann
- [Bayesian SEM with brms](http://rpubs.com/jebyrnes/brms_bayes_sem/) by Jarrett Byrnes
- [Diffusion/Wiener Model Analysis with brms – Part I: Introduction and Estimation](http://singmann.org/wiener-model-analysis-with-brms-part-i/) by Henrik Singmann
- [Bayesian Decision Theory Made Ridiculously Simple ](http://www.statsathome.com/2017/10/12/bayesian-decision-theory-made-ridiculously-simple/) by Justin Silverman
- [Bayesian Estimation of Signal Detection Models, Part 4](https://vuorre.netlify.com/post/2017/bayesian-estimation-of-signal-detection-theory-models-part-4/) by Matti Vuorre
- [Bayesian Estimation of Signal Detection Models, Part 3](https://vuorre.netlify.com/post/2017/bayesian-estimation-of-signal-detection-theory-models-part-3/) by Matti Vuorre
- [Bayesian Estimation of Signal Detection Models, Part 2](https://vuorre.netlify.com/post/2017/bayesian-estimation-of-signal-detection-theory-models-part-2/) by Matti Vuorre
- [Bayesian Estimation of Signal Detection Models, Part 1](https://vuorre.netlify.com/post/2017/bayesian-estimation-of-signal-detection-theory-models-part-1/) by Matti Vuorre
- [Three methods for computing the intra-class correlation in multilevel logistic regression](http://www.barelysignificant.com/post/icc/) by Ladislas Nalborczyk
- [More support for Bayesian analysis in the sj!-packages #rstats #rstan #brms](https://strengejacke.wordpress.com/2017/10/11/more-support-for-bayesian-analysis-in-the-sj-packages-rstats-rstan-brms/) by Daniel Luedecke
- [R packages interfacing with Stan: brms](http://andrewgelman.com/2017/01/10/r-packages-interfacing-stan-brms/) by Paul Buerkner
- [Bayesian mixed effects (aka multi-level) ordinal regression models with brms](http://kevinstadler.github.io/blog/bayesian-ordinal-regression-with-random-effects-using-brms/) by Kevin Stadler
- [Bayes factors with brms](https://vuorre.netlify.com/post/2017/bayes-factors-with-brms/) by Matti Vuorre
- [How to Compare Two Groups with Robust Bayesian Estimation Using R, Stan and brms](https://vuorre.netlify.com/post/2017/how-to-compare-two-groups-with-robust-bayesian-estimation-using-r-stan-and-brms/) by Matti Vuorre
- [Better forest plots from meta-analytic models estimated with brms](https://vuorre.netlify.com/post/2017/better-brms-forest-plots/) by Matti Vuorre
- [Meta-analysis is a special case of Bayesian multilevel modeling](https://vuorre.netlify.com/post/2016/2016-09-29-bayesian-meta-analysis/) by Matti Vuorre
- [brms continuous its streak](https://thinkinator.com/2016/11/20/brms-continues-its-streak/) by Wayne Folta
- [brms 0.8 adds non-linear regression](https://thinkinator.com/2016/02/17/brms-0-8-adds-non-linear-regression/) by Wayne Folta
- [R Users Will Now Inevitably Become Bayesians](https://thinkinator.com/2016/01/12/r-users-will-now-inevitably-become-bayesians/) by Wayne Folta
- [Bayesian regression models using Stan in R ](http://www.magesblog.com/2015/09/bayesian-regression-models-using-stan.html) by Markus Gesmann
