test_that(" create_filename_auto works", {
  a  <- create_filename_auto("a", "b", FALSE, nlist(a = 5))
  a_exp <- nlist( file = "a", file_refit = "b")
  expect_equal(a , a_exp)
  a  <- create_filename_auto(NA, NULL, FALSE, nlist(a = 5, family = gaussian()))
  a_exp <- nlist( file = NA, file_refit = NULL)
  expect_equal(a , a_exp)
  a  <- create_filename_auto("a", "b", FALSE, nlist(a = 5, family = gaussian()))
  a_exp <- nlist( file = "a", file_refit = "b")
  expect_equal(a, a_exp)
})
