# Posterior-equivalence validation for physical S2Z group effects with
# coefficient- and group-specific scales.
#
# This local test compares the Stan program generated by the development brms
# build against standalone conventional models having exactly
#
#   log(sd_level[j, k]) = log(sd[k]) + sdlog[k] * z_scale[j, k],
#   z_scale[j, k] ~ normal(0, 1).
#
# The Gaussian case has correlated varying intercepts, slopes, and an
# interaction. The Student case has an intercept and slope with a diagonal
# scale matrix and the same one-per-group inverse-chi-square mixture used by
# brms. Both references put the intercept prior on the centered-X intercept,
# matching brms rather than an uncentered approximation.
#
# Run against an installed development build, for example:
#
#   R_LIBS=/path/to/development-library \
#     Rscript tests/local/tests.models-s2z-varying-scale.R
#
# Runtime controls (defaults shown):
#
#   BRMS_S2Z_VS_CASES=gaussian,student
#   BRMS_S2Z_VS_CHAINS=2
#   BRMS_S2Z_VS_WARMUP=400
#   BRMS_S2Z_VS_SAMPLING=400
#   BRMS_S2Z_VS_CORES=min(chains, physical cores)
#   BRMS_S2Z_VS_ADAPT_DELTA=0.98
#   BRMS_S2Z_VS_MAX_TREEDEPTH=12
#   BRMS_S2Z_VS_EQUIV_Z=7
#   BRMS_S2Z_VS_EQUIV_ABS=0.06
#   BRMS_S2Z_VS_EQUIV_REL=0.125
#   BRMS_S2Z_VS_MAX_RHAT=1.10
#   BRMS_S2Z_VS_MIN_BULK_ESS=40
#   BRMS_S2Z_VS_MIN_TAIL_ESS=50
#   BRMS_S2Z_VS_MAX_DIVERGENCES=0
#   BRMS_S2Z_VS_MAX_TREEDEPTH_HITS=0
#   BRMS_S2Z_VS_INVARIANT_TOL=1e-6
#   BRMS_S2Z_VS_REFRESH=0
#   BRMS_S2Z_VS_CACHE_DIR=
#   BRMS_S2Z_VS_OUTPUT_DIR=
#
# Posterior means, SDs, and 10%, 50%, and 90% quantiles are compared using
# both the propagated MCSE of the two independent fits and prespecified
# absolute-plus-relative tolerances. Set BRMS_S2Z_VS_OUTPUT_DIR to retain full
# CSV outcomes and their exact source provenance.

suppressPackageStartupMessages({
  library(brms)
  library(cmdstanr)
  library(posterior)
})

env_integer <- function(name, default, minimum = 1L) {
  value <- Sys.getenv(name, unset = "")
  if (!nzchar(value)) {
    return(as.integer(default))
  }
  out <- suppressWarnings(as.integer(value))
  if (length(out) != 1L || is.na(out) || out < minimum) {
    stop(name, " must be an integer >= ", minimum, call. = FALSE)
  }
  out
}

env_number <- function(name, default, minimum = -Inf) {
  value <- Sys.getenv(name, unset = "")
  if (!nzchar(value)) {
    return(as.numeric(default))
  }
  out <- suppressWarnings(as.numeric(value))
  if (length(out) != 1L || !is.finite(out) || out < minimum) {
    stop(name, " must be a finite number >= ", minimum, call. = FALSE)
  }
  out
}

script_path <- function() {
  arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
  if (length(arg)) {
    return(normalizePath(sub("^--file=", "", arg[[1L]])))
  }
  normalizePath(file.path("tests", "local", "tests.models-s2z-varying-scale.R"))
}

requested_cases <- strsplit(
  tolower(Sys.getenv("BRMS_S2Z_VS_CASES", unset = "gaussian,student")),
  ",", fixed = TRUE
)[[1L]]
requested_cases <- trimws(requested_cases)
allowed_cases <- c("gaussian", "student")
if (!length(requested_cases) || any(!requested_cases %in% allowed_cases)) {
  stop("BRMS_S2Z_VS_CASES must contain gaussian and/or student.",
       call. = FALSE)
}

chains <- env_integer("BRMS_S2Z_VS_CHAINS", 2L, minimum = 2L)
warmup <- env_integer("BRMS_S2Z_VS_WARMUP", 400L)
sampling <- env_integer("BRMS_S2Z_VS_SAMPLING", 400L)
detected_cores <- parallel::detectCores(logical = FALSE)
if (is.na(detected_cores)) {
  detected_cores <- 1L
}
cores <- env_integer(
  "BRMS_S2Z_VS_CORES", min(chains, detected_cores), minimum = 1L
)
adapt_delta <- env_number(
  "BRMS_S2Z_VS_ADAPT_DELTA", 0.98, minimum = 0.5
)
max_treedepth <- env_integer("BRMS_S2Z_VS_MAX_TREEDEPTH", 12L)
equiv_z <- env_number("BRMS_S2Z_VS_EQUIV_Z", 7, minimum = 1)
equiv_abs <- env_number("BRMS_S2Z_VS_EQUIV_ABS", 0.06, minimum = 0)
equiv_rel <- env_number("BRMS_S2Z_VS_EQUIV_REL", 0.125, minimum = 0)
max_rhat <- env_number("BRMS_S2Z_VS_MAX_RHAT", 1.10, minimum = 1)
min_bulk_ess <- env_number("BRMS_S2Z_VS_MIN_BULK_ESS", 40, minimum = 0)
min_tail_ess <- env_number("BRMS_S2Z_VS_MIN_TAIL_ESS", 50, minimum = 0)
max_divergences <- env_integer(
  "BRMS_S2Z_VS_MAX_DIVERGENCES", 0L, minimum = 0L
)
max_treedepth_hits <- env_integer(
  "BRMS_S2Z_VS_MAX_TREEDEPTH_HITS", 0L, minimum = 0L
)
invariant_tolerance <- env_number(
  "BRMS_S2Z_VS_INVARIANT_TOL", 1e-6, minimum = 0
)
refresh <- env_integer("BRMS_S2Z_VS_REFRESH", 0L, minimum = 0L)
cache_dir <- Sys.getenv("BRMS_S2Z_VS_CACHE_DIR", unset = "")
output_dir <- Sys.getenv("BRMS_S2Z_VS_OUTPUT_DIR", unset = "")
local_dir <- dirname(script_path())

git_sha <- tryCatch(
  system2("git", c("rev-parse", "HEAD"), stdout = TRUE, stderr = FALSE)[1L],
  error = function(e) NA_character_
)
git_dirty <- tryCatch(
  length(system2(
    "git", c("status", "--porcelain", "--untracked-files=no"),
    stdout = TRUE, stderr = FALSE
  )) > 0L,
  error = function(e) NA
)
source_files <- c(
  script_path(),
  file.path(local_dir, "s2z-varying-scale-conventional-gaussian.stan"),
  file.path(local_dir, "s2z-varying-scale-conventional-student.stan")
)
source_md5 <- tools::md5sum(source_files)
source_provenance <- paste(
  paste0(basename(source_files), "=", unname(source_md5)), collapse = ";"
)

if (!nzchar(tryCatch(cmdstanr::cmdstan_path(), error = function(e) ""))) {
  stop("This local equivalence harness requires a working CmdStan install.",
       call. = FALSE)
}

options(mc.cores = cores, width = 150)

configuration <- data.frame(
  brms_version = as.character(utils::packageVersion("brms")),
  cmdstan_version = as.character(cmdstanr::cmdstan_version()),
  cases = paste(requested_cases, collapse = ","),
  chains = chains,
  warmup = warmup,
  sampling = sampling,
  cores = cores,
  adapt_delta = adapt_delta,
  max_treedepth = max_treedepth,
  equiv_z = equiv_z,
  equiv_abs = equiv_abs,
  equiv_rel = equiv_rel,
  max_rhat = max_rhat,
  min_bulk_ess = min_bulk_ess,
  min_tail_ess = min_tail_ess,
  max_divergences = max_divergences,
  max_treedepth_hits = max_treedepth_hits,
  invariant_tolerance = invariant_tolerance,
  case_seeds = "gaussian:8301;student:8302",
  git_sha = git_sha,
  git_dirty = git_dirty,
  source_md5 = source_provenance,
  refresh = refresh,
  stringsAsFactors = FALSE
)
cat("Group-varying-scale S2Z equivalence configuration\n")
print(configuration, row.names = FALSE)

rmvn_one <- function(L) {
  drop(L %*% stats::rnorm(nrow(L)))
}

simulate_gaussian <- function(seed = 7301L, groups = 8L,
                              per_group = 20L) {
  set.seed(seed)
  levels_g <- sprintf("g%02d", seq_len(groups))
  base_grid <- expand.grid(x = c(-0.8, 1.2), z = c(-1.3, 0.7))
  dat <- do.call(rbind, lapply(seq_len(groups), function(j) {
    grid <- base_grid[rep(seq_len(nrow(base_grid)),
                          length.out = per_group), ]
    data.frame(
      g = levels_g[j],
      x = grid$x + stats::rnorm(per_group, sd = 0.12),
      z = grid$z + stats::rnorm(per_group, sd = 0.12)
    )
  }))
  rownames(dat) <- NULL
  dat$g <- factor(dat$g, levels = levels_g)
  X <- stats::model.matrix(~ x * z, dat)
  beta <- c(0.35, 0.70, -0.50, 0.38)
  baseline_sd <- c(0.55, 0.38, 0.32, 0.26)
  sdlog <- c(0.18, 0.28, 0.22, 0.34)
  Cor <- outer(seq_along(baseline_sd), seq_along(baseline_sd),
               function(i, j) 0.30^abs(i - j))
  L_cor <- t(chol(Cor))
  z_scale <- matrix(stats::rnorm(groups * ncol(X)), groups, ncol(X))
  sd_level <- exp(sweep(z_scale, 2L, sdlog, "*"))
  sd_level <- sweep(sd_level, 2L, baseline_sd, "*")
  u <- matrix(NA_real_, groups, ncol(X))
  for (j in seq_len(groups)) {
    u[j, ] <- rmvn_one(diag(sd_level[j, ]) %*% L_cor)
  }
  eta <- drop(X %*% beta) + rowSums(X * u[as.integer(dat$g), ])
  dat$y <- stats::rnorm(nrow(dat), eta, 0.28)
  dat
}

simulate_student <- function(seed = 7302L, groups = 10L,
                             per_group = 16L, df = 6) {
  set.seed(seed)
  levels_g <- sprintf("g%02d", seq_len(groups))
  dat <- do.call(rbind, lapply(seq_len(groups), function(j) {
    data.frame(
      g = levels_g[j],
      x = seq(-1.2, 1.5, length.out = per_group) +
        stats::rnorm(per_group, sd = 0.10)
    )
  }))
  rownames(dat) <- NULL
  dat$g <- factor(dat$g, levels = levels_g)
  X <- stats::model.matrix(~ x, dat)
  beta <- c(-0.20, 0.78)
  baseline_sd <- c(0.62, 0.42)
  sdlog <- c(0.20, 0.30)
  z_scale <- matrix(stats::rnorm(groups * ncol(X)), groups, ncol(X))
  sd_level <- exp(sweep(z_scale, 2L, sdlog, "*"))
  sd_level <- sweep(sd_level, 2L, baseline_sd, "*")
  student_scale <- sqrt(df / stats::rchisq(groups, df = df))
  u <- matrix(stats::rnorm(groups * ncol(X)), groups, ncol(X))
  u <- u * sd_level * student_scale
  eta <- drop(X %*% beta) + rowSums(X * u[as.integer(dat$g), ])
  dat$y <- stats::rnorm(nrow(dat), eta, 0.32)
  dat
}

case_prior <- function(coefs, sd_rate, sdlog_scale,
                       student = FALSE, correlated = FALSE) {
  stopifnot(
    length(coefs) == length(sd_rate),
    length(coefs) == length(sdlog_scale)
  )
  out <- prior(normal(0, 1.5), class = "Intercept") +
    prior(normal(0, 1.5), class = "b") +
    prior(exponential(1), class = "sigma")
  for (k in seq_along(coefs)) {
    out <- out + prior_string(
      sprintf("exponential(%.17g)", sd_rate[k]),
      class = "sd", group = "g", coef = coefs[k]
    ) + prior_string(
      sprintf("normal(0, %.17g)", sdlog_scale[k]),
      class = "sdlog", group = "g", coef = coefs[k]
    )
  }
  if (correlated) {
    out <- out + prior(lkj(2), class = "cor", group = "g")
  }
  if (student) {
    out <- out + prior(gamma(2, 0.2), class = "df", group = "g")
  }
  out
}

make_case <- function(name) {
  if (name == "gaussian") {
    data <- simulate_gaussian()
    formula <- bf(
      y ~ x * z +
        (1 + x * z | gr(g, s2z = TRUE, scale = "varying"))
    )
    coefs <- c("Intercept", "x", "z", "x:z")
    sd_rate <- c(0.8, 1.1, 1.4, 1.7)
    sdlog_scale <- c(0.12, 0.17, 0.22, 0.27)
    list(
      name = "correlated-gaussian-interaction", data = data,
      formula = formula, fixed_formula = ~ x * z,
      prior = case_prior(
        coefs, sd_rate, sdlog_scale, correlated = TRUE
      ),
      sd_rate = sd_rate, sdlog_scale = sdlog_scale, correlated = TRUE,
      student = FALSE,
      stan = "s2z-varying-scale-conventional-gaussian.stan",
      seed = 8301L
    )
  } else {
    data <- simulate_student()
    formula <- bf(
      y ~ x +
        (1 + x | gr(
          g, cor = FALSE, dist = "student", s2z = TRUE,
          scale = "varying"
        ))
    )
    coefs <- c("Intercept", "x")
    sd_rate <- c(0.9, 1.5)
    sdlog_scale <- c(0.15, 0.26)
    list(
      name = "diagonal-student-intercept-slope", data = data,
      formula = formula, fixed_formula = ~ x,
      prior = case_prior(
        coefs, sd_rate, sdlog_scale, student = TRUE
      ),
      sd_rate = sd_rate, sdlog_scale = sdlog_scale, correlated = FALSE,
      student = TRUE,
      stan = "s2z-varying-scale-conventional-student.stan",
      seed = 8302L
    )
  }
}

cache_file <- function(label) {
  if (!nzchar(cache_dir)) {
    return(NULL)
  }
  dir.create(cache_dir, recursive = TRUE, showWarnings = FALSE)
  suffix <- paste(chains, warmup, sampling, sep = "-")
  file.path(cache_dir, paste0(label, "-", suffix, ".rds"))
}

sample_brms <- function(case) {
  cat("\nSampling actual brms S2Z model: ", case$name, " ...\n", sep = "")
  args <- list(
    formula = case$formula,
    data = case$data,
    family = gaussian(),
    prior = case$prior,
    backend = "cmdstanr",
    chains = chains,
    cores = cores,
    iter = warmup + sampling,
    warmup = warmup,
    seed = case$seed,
    refresh = refresh,
    silent = 1,
    save_pars = save_pars(all = TRUE),
    control = list(
      adapt_delta = adapt_delta,
      max_treedepth = max_treedepth
    )
  )
  file <- cache_file(paste0(case$name, "-brms-s2z"))
  if (!is.null(file)) {
    args$file <- file
    args$file_refit <- "on_change"
  }
  do.call(brm, args)
}

reference_build_dir <- function() {
  if (nzchar(cache_dir)) {
    out <- file.path(cache_dir, "conventional-stan")
    dir.create(out, recursive = TRUE, showWarnings = FALSE)
    return(out)
  }
  tempfile("brms-s2z-varying-scale-reference-")
}

reference_model <- function(case) {
  source <- file.path(local_dir, case$stan)
  if (!file.exists(source)) {
    stop("Missing conventional Stan reference: ", source, call. = FALSE)
  }
  build_dir <- reference_build_dir()
  dir.create(build_dir, recursive = TRUE, showWarnings = FALSE)
  target <- file.path(build_dir, basename(source))
  same <- file.exists(target) && identical(
    unname(tools::md5sum(source)), unname(tools::md5sum(target))
  )
  if (!same && !file.copy(source, target, overwrite = TRUE)) {
    stop("Could not copy the conventional reference into its build cache.",
         call. = FALSE)
  }
  cmdstanr::cmdstan_model(target, quiet = TRUE)
}

reference_data <- function(case, sdata) {
  X <- unname(sdata$X)
  Z_names <- sprintf("Z_1_%d", seq_len(sdata$M_1))
  Z <- do.call(cbind, unclass(sdata[Z_names]))
  means_X <- colMeans(X[, -1L, drop = FALSE])
  out <- list(
    N = sdata$N,
    J = sdata$N_1,
    M = sdata$M_1,
    y = unname(sdata$Y),
    Xc = sweep(X[, -1L, drop = FALSE], 2L, means_X, "-"),
    Z = unname(Z),
    means_X = unname(means_X),
    group = as.integer(sdata$J_1),
    beta_prior_sd = 1.5,
    sd_prior_rate = case$sd_rate,
    sdlog_prior_sd = case$sdlog_scale,
    sigma_prior_rate = 1
  )
  if (case$correlated) {
    out$lkj_eta <- 2
  }
  if (case$student) {
    out$df_prior_shape <- 2
    out$df_prior_rate <- 0.2
  }
  out
}

sample_reference <- function(case, sdata) {
  cat("Sampling standalone conventional model: ", case$name, " ...\n",
      sep = "")
  model <- reference_model(case)
  model$sample(
    data = reference_data(case, sdata),
    seed = case$seed + 1000L,
    chains = chains,
    parallel_chains = min(chains, cores),
    iter_warmup = warmup,
    iter_sampling = sampling,
    refresh = refresh,
    adapt_delta = adapt_delta,
    max_treedepth = max_treedepth
  )
}

draw_matrix <- function(draws, variable) {
  available <- posterior::variables(draws)
  if (!variable %in% available) {
    stop("Required draw variable is missing: ", variable, call. = FALSE)
  }
  d <- dim(draws)
  out <- draws[, , variable, drop = TRUE]
  matrix(out, nrow = d[1L], ncol = d[2L])
}

add_quantity <- function(x, name, value) {
  x[[name]] <- value
  x
}

coefficient_names <- function(case) {
  out <- colnames(stats::model.matrix(case$fixed_formula, case$data))
  sub("^\\(Intercept\\)$", "Intercept", out)
}

brms_quantities <- function(fit, case, sdata) {
  draws <- posterior::as_draws_array(fit)
  coefs <- coefficient_names(case)
  levels_g <- levels(case$data$g)
  M <- length(coefs)
  J <- length(levels_g)
  out <- list()
  b <- vector("list", M)
  r <- matrix(vector("list", J * M), J, M)

  for (k in seq_len(M)) {
    b[[k]] <- draw_matrix(draws, paste0("b_", coefs[k]))
    out <- add_quantity(out, paste0("b:", coefs[k]), b[[k]])
    out <- add_quantity(
      out, paste0("sd:", coefs[k]),
      draw_matrix(draws, paste0("sd_g__", coefs[k]))
    )
    out <- add_quantity(
      out, paste0("sdlog:", coefs[k]),
      draw_matrix(draws, paste0("sdlog_g__", coefs[k]))
    )
    for (j in seq_len(J)) {
      r[[j, k]] <- draw_matrix(
        draws, sprintf("r_g[%s,%s]", levels_g[j], coefs[k])
      )
      out <- add_quantity(
        out, sprintf("r:%s,%s", levels_g[j], coefs[k]), r[[j, k]]
      )
      out <- add_quantity(
        out, sprintf("b+r:%s,%s", levels_g[j], coefs[k]),
        b[[k]] + r[[j, k]]
      )
      out <- add_quantity(
        out, sprintf("sd_level:%s,%s", levels_g[j], coefs[k]),
        draw_matrix(
          draws, sprintf("sd_level_g[%s,%s]", levels_g[j], coefs[k])
        )
      )
    }
  }

  centered_intercept <- b[[1L]]
  for (k in 2 : M) {
    centered_intercept <- centered_intercept +
      colMeans(sdata$X)[k] * b[[k]]
  }
  out <- add_quantity(out, "b:centered-Intercept", centered_intercept)
  out <- add_quantity(out, "parameter:sigma", draw_matrix(draws, "sigma"))

  if (case$student) {
    out <- add_quantity(out, "parameter:df", draw_matrix(draws, "df_g"))
  }
  if (case$correlated) {
    for (k in 2 : M) {
      for (j in seq_len(k - 1L)) {
        out <- add_quantity(
          out, sprintf("cor:%s,%s", coefs[j], coefs[k]),
          draw_matrix(draws, sprintf("cor_g__%s__%s", coefs[j], coefs[k]))
        )
      }
    }
  }

  eta_average <- matrix(0, nrow(b[[1L]]), ncol(b[[1L]]))
  selected_obs <- unique(round(seq(1, nrow(case$data), length.out = 6L)))
  for (n in seq_len(nrow(case$data))) {
    eta_n <- matrix(0, nrow(b[[1L]]), ncol(b[[1L]]))
    group_n <- as.integer(case$data$g[n])
    for (k in seq_len(M)) {
      eta_n <- eta_n + sdata$X[n, k] * (b[[k]] + r[[group_n, k]])
    }
    eta_average <- eta_average + eta_n / nrow(case$data)
    if (n %in% selected_obs) {
      out <- add_quantity(out, sprintf("eta:observation[%d]", n), eta_n)
    }
  }
  add_quantity(out, "eta:observation-average", eta_average)
}

reference_quantities <- function(fit, case, sdata) {
  draws <- fit$draws(format = "draws_array")
  coefs <- coefficient_names(case)
  levels_g <- levels(case$data$g)
  M <- length(coefs)
  J <- length(levels_g)
  out <- list()

  for (k in seq_len(M)) {
    out <- add_quantity(
      out, paste0("b:", coefs[k]),
      draw_matrix(draws, sprintf("b_public[%d]", k))
    )
    out <- add_quantity(
      out, paste0("sd:", coefs[k]),
      draw_matrix(draws, sprintf("sd[%d]", k))
    )
    out <- add_quantity(
      out, paste0("sdlog:", coefs[k]),
      draw_matrix(draws, sprintf("sdlog[%d]", k))
    )
    for (j in seq_len(J)) {
      out <- add_quantity(
        out, sprintf("r:%s,%s", levels_g[j], coefs[k]),
        draw_matrix(draws, sprintf("r[%d,%d]", j, k))
      )
      out <- add_quantity(
        out, sprintf("b+r:%s,%s", levels_g[j], coefs[k]),
        draw_matrix(draws, sprintf("finite_coefficient[%d,%d]", j, k))
      )
      out <- add_quantity(
        out, sprintf("sd_level:%s,%s", levels_g[j], coefs[k]),
        draw_matrix(draws, sprintf("sd_level[%d,%d]", j, k))
      )
    }
  }

  out <- add_quantity(
    out, "b:centered-Intercept", draw_matrix(draws, "beta_centered[1]")
  )
  out <- add_quantity(out, "parameter:sigma", draw_matrix(draws, "sigma"))
  if (case$student) {
    out <- add_quantity(out, "parameter:df", draw_matrix(draws, "df"))
  }
  if (case$correlated) {
    for (k in 2 : M) {
      for (j in seq_len(k - 1L)) {
        out <- add_quantity(
          out, sprintf("cor:%s,%s", coefs[j], coefs[k]),
          draw_matrix(draws, sprintf("Cor[%d,%d]", j, k))
        )
      }
    }
  }

  selected_obs <- unique(round(seq(1, nrow(case$data), length.out = 6L)))
  mu_average <- matrix(0, nrow(draw_matrix(draws, "mu[1]")),
                       ncol(draw_matrix(draws, "mu[1]")))
  for (n in seq_len(nrow(case$data))) {
    mu_n <- draw_matrix(draws, sprintf("mu[%d]", n))
    mu_average <- mu_average + mu_n / nrow(case$data)
    if (n %in% selected_obs) {
      out <- add_quantity(
        out, sprintf("eta:observation[%d]", n), mu_n
      )
    }
  }
  add_quantity(out, "eta:observation-average", mu_average)
}

one_variable_draws <- function(x, name = "x") {
  out <- array(
    x,
    dim = c(nrow(x), ncol(x), 1L),
    dimnames = list(
      iteration = NULL,
      chain = paste0("chain", seq_len(ncol(x))),
      variable = name
    )
  )
  posterior::as_draws_array(out)
}

quantity_summary <- function(x) {
  draws <- one_variable_draws(x)
  ans <- posterior::summarise_draws(
    draws,
    mean = base::mean,
    sd = stats::sd,
    mcse_mean = posterior::mcse_mean,
    mcse_sd = posterior::mcse_sd,
    rhat = posterior::rhat,
    ess_bulk = posterior::ess_bulk,
    ess_tail = posterior::ess_tail
  )
  out <- as.list(ans[1L, c(
    "mean", "sd", "mcse_mean", "mcse_sd", "rhat", "ess_bulk", "ess_tail"
  )])
  quantiles <- stats::quantile(c(x), probs = c(0.1, 0.5, 0.9))
  names(quantiles) <- c("q10", "q50", "q90")
  quantile_mcse <- posterior::mcse_quantile(
    draws, probs = c(0.1, 0.5, 0.9)
  )
  c(out, as.list(quantiles), as.list(quantile_mcse))
}

compare_quantities <- function(reference, s2z, case_name) {
  if (!setequal(names(reference), names(s2z))) {
    stop(
      "Canonical quantities differ. Only reference: ",
      paste(setdiff(names(reference), names(s2z)), collapse = ", "),
      "; only S2Z: ",
      paste(setdiff(names(s2z), names(reference)), collapse = ", "),
      call. = FALSE
    )
  }
  rows <- list()
  row <- 0L
  for (name in sort(names(reference))) {
    x <- quantity_summary(reference[[name]])
    y <- quantity_summary(s2z[[name]])
    for (metric in c("mean", "sd", "q10", "q50", "q90")) {
      row <- row + 1L
      mcse_name <- paste0("mcse_", metric)
      difference <- y[[metric]] - x[[metric]]
      mcse_difference <- sqrt(x[[mcse_name]]^2 + y[[mcse_name]]^2)
      z_score <- if (is.finite(mcse_difference) && mcse_difference > 0) {
        abs(difference) / mcse_difference
      } else if (identical(x[[metric]], y[[metric]])) {
        0
      } else {
        Inf
      }
      equiv_margin <- equiv_abs + equiv_rel * max(
        abs(x[[metric]]), abs(y[[metric]])
      )
      mcse_pass <- is.finite(z_score) && z_score <= equiv_z
      margin_pass <- is.finite(difference) &&
        abs(difference) <= equiv_margin
      rows[[row]] <- data.frame(
        case = case_name,
        quantity = name,
        metric = metric,
        conventional = x[[metric]],
        s2z = y[[metric]],
        difference = difference,
        mcse_difference = mcse_difference,
        z_score = z_score,
        equiv_margin = equiv_margin,
        mcse_pass = mcse_pass,
        margin_pass = margin_pass,
        pass = mcse_pass && margin_pass,
        stringsAsFactors = FALSE
      )
    }
  }
  out <- do.call(rbind, rows)
  out[order(out$z_score, decreasing = TRUE), ]
}

s2z_basis <- function(n) {
  constrain <- function(y) {
    z <- numeric(length(y) + 1L)
    sum_w <- 0
    for (ii in seq_along(y)) {
      i <- length(y) - ii + 1L
      w <- y[i] / sqrt(i * (i + 1))
      sum_w <- sum_w + w
      z[i] <- z[i] + sum_w
      z[i + 1L] <- z[i + 1L] - i * w
    }
    z
  }
  vapply(
    seq_len(n - 1L),
    function(j) constrain(diag(n - 1L)[, j]),
    numeric(n)
  )
}

s2z_invariants <- function(fit, case, sdata, canonical) {
  draws <- posterior::as_draws_array(fit)
  coefs <- coefficient_names(case)
  levels_g <- levels(case$data$g)
  M <- length(coefs)
  J <- length(levels_g)
  B <- s2z_basis(J)
  theta <- lapply(seq_len(M), function(k) {
    draw_matrix(draws, sprintf("theta_s2z[%d]", k))
  })
  raw_theta_intercept <- theta[[1L]]
  for (k in 2 : M) {
    raw_theta_intercept <- raw_theta_intercept -
      colMeans(sdata$X)[k] * theta[[k]]
  }

  max_scale_error <- 0
  max_scale_sum_error <- 0
  max_geomean_error <- 0
  max_finite_error <- 0
  max_predictor_error <- 0
  physical_finite <- matrix(vector("list", J * M), J, M)

  for (k in seq_len(M)) {
    raw_scale <- do.call(cbind, lapply(seq_len(J - 1L), function(j) {
      c(draw_matrix(
        draws, sprintf("z_sd_s2z_1[%d,%d]", k, j)
      ))
    }))
    z_centered <- raw_scale %*% t(B)
    z_mean <- draw_matrix(
      draws, sprintf("z_sd_mean_s2z_1[%d]", k)
    )
    baseline_sd <- canonical[[paste0("sd:", coefs[k])]]
    sdlog <- canonical[[paste0("sdlog:", coefs[k])]]
    expected_geomean <- baseline_sd * exp(sdlog * z_mean / sqrt(J))
    saved_scale <- vector("list", J)
    for (j in seq_len(J)) {
      expected <- baseline_sd * exp(
        sdlog * (z_centered[, j] + z_mean / sqrt(J))
      )
      saved_scale[[j]] <- canonical[[
        sprintf("sd_level:%s,%s", levels_g[j], coefs[k])
      ]]
      max_scale_error <- max(max_scale_error, abs(expected - saved_scale[[j]]))
    }
    log_saved <- Reduce("+", lapply(saved_scale, log)) / J
    max_geomean_error <- max(
      max_geomean_error, abs(exp(log_saved) - expected_geomean)
    )
    max_scale_sum_error <- max(
      max_scale_sum_error, abs(rowSums(z_centered))
    )

    for (j in seq_len(J)) {
      internal_r_name <- if (case$correlated) {
        sprintf("r_s2z_1[%d,%d]", j, k)
      } else {
        sprintf("r_s2z_1_%d[%d]", k, j)
      }
      contrast <- draw_matrix(draws, internal_r_name)
      physical_finite[[j, k]] <- if (k == 1L) {
        raw_theta_intercept + contrast
      } else {
        theta[[k]] + contrast
      }
      public_finite <- canonical[[
        sprintf("b+r:%s,%s", levels_g[j], coefs[k])
      ]]
      max_finite_error <- max(
        max_finite_error, abs(physical_finite[[j, k]] - public_finite)
      )
    }
  }

  for (n in seq_len(nrow(case$data))) {
    group_n <- as.integer(case$data$g[n])
    eta_physical <- matrix(
      0, nrow(theta[[1L]]), ncol(theta[[1L]])
    )
    for (k in seq_len(M)) {
      eta_physical <- eta_physical +
        sdata$X[n, k] * physical_finite[[group_n, k]]
    }
    eta_public <- matrix(
      0, nrow(theta[[1L]]), ncol(theta[[1L]])
    )
    for (k in seq_len(M)) {
      eta_public <- eta_public + sdata$X[n, k] * canonical[[
        sprintf("b+r:%s,%s", levels_g[group_n], coefs[k])
      ]]
    }
    max_predictor_error <- max(
      max_predictor_error, abs(eta_physical - eta_public)
    )
  }

  out <- data.frame(
    case = case$name,
    check = c(
      "orthonormal log-scale contrasts sum to zero",
      "sd_level equals sd * exp(sdlog * z_level)",
      "sd_level geometric mean equals reference scale",
      "public b+r equals physical theta+contrast",
      "public predictor equals physical S2Z predictor"
    ),
    max_abs_error = c(
      max_scale_sum_error, max_scale_error, max_geomean_error,
      max_finite_error, max_predictor_error
    ),
    tolerance = invariant_tolerance,
    stringsAsFactors = FALSE
  )
  out$pass <- out$max_abs_error <= out$tolerance
  out
}

s2z_public_api_invariants <- function(fit, case, canonical) {
  coefs <- coefficient_names(case)
  levels_g <- levels(case$data$g)
  M <- length(coefs)
  J <- length(levels_g)
  ndraws <- length(canonical[["b:Intercept"]])

  fe <- fixef(fit, summary = FALSE)
  re <- ranef(fit, summary = FALSE)$g
  cf <- coef(fit, summary = FALSE)$g
  extractor_ok <- identical(dim(fe), c(ndraws, M)) &&
    identical(dim(re), c(ndraws, J, M)) &&
    identical(dim(cf), c(ndraws, J, M)) &&
    setequal(colnames(fe), coefs) &&
    identical(dimnames(re)[[2L]], levels_g) &&
    identical(dimnames(re)[[3L]], coefs)
  max_extractor_error <- 0
  if (extractor_ok) {
    for (k in seq_len(M)) {
      max_extractor_error <- max(
        max_extractor_error,
        abs(fe[, k] - c(canonical[[paste0("b:", coefs[k])]]))
      )
      for (j in seq_len(J)) {
        max_extractor_error <- max(
          max_extractor_error,
          abs(re[, j, k] - c(canonical[[sprintf(
            "r:%s,%s", levels_g[j], coefs[k]
          )]])),
          abs(cf[, j, k] - c(canonical[[sprintf(
            "b+r:%s,%s", levels_g[j], coefs[k]
          )]]))
        )
      }
    }
  } else {
    max_extractor_error <- Inf
  }

  vc_raw <- VarCorr(fit, summary = FALSE)$g
  varcorr_shape_ok <- identical(dim(vc_raw$sdlog), c(ndraws, M)) &&
    identical(dim(vc_raw$sd_level), c(ndraws, J, M)) &&
    length(vc_raw$cov_level) == J &&
    all(vapply(
      vc_raw$cov_level,
      function(x) identical(dim(x), c(ndraws, M, M)),
      logical(1)
    ))
  max_scale_error <- 0
  max_cov_error <- 0
  if (varcorr_shape_ok) {
    for (j in seq_len(J)) {
      scale_j <- vector("list", M)
      for (k in seq_len(M)) {
        scale_j[[k]] <- c(canonical[[
          sprintf("sd_level:%s,%s", levels_g[j], coefs[k])
        ]])
        max_scale_error <- max(
          max_scale_error,
          abs(vc_raw$sd_level[, j, k] - scale_j[[k]])
        )
      }
      for (k in seq_len(M)) {
        for (l in seq_len(M)) {
          if (k == l) {
            expected_cov <- scale_j[[k]]^2
          } else if (case$correlated) {
            pair <- sort(c(k, l))
            correlation <- c(canonical[[sprintf(
              "cor:%s,%s", coefs[pair[1L]], coefs[pair[2L]]
            )]])
            expected_cov <- scale_j[[k]] * scale_j[[l]] * correlation
          } else {
            expected_cov <- numeric(ndraws)
          }
          max_cov_error <- max(
            max_cov_error,
            abs(vc_raw$cov_level[[j]][, k, l] - expected_cov)
          )
        }
      }
    }
  } else {
    max_scale_error <- max_cov_error <- Inf
  }

  vc_summary <- VarCorr(fit, summary = TRUE)$g
  summary_shape_ok <- identical(dim(vc_summary$sdlog), c(M, 4L)) &&
    identical(dim(vc_summary$sd_level), c(J, 4L, M)) &&
    length(vc_summary$cov_level) == J &&
    all(vapply(
      vc_summary$cov_level,
      function(x) identical(dim(x), c(M, 4L, M)),
      logical(1)
    ))
  fit_summary <- summary(fit)
  summary_sdlog_ok <- all(
    paste0("sdlog(", coefs, ")") %in% rownames(fit_summary$random$g)
  )

  checks <- data.frame(
    case = case$name,
    check = c(
      "fixef/ranef/coef expose conventional shapes and names",
      "fixef/ranef/coef equal conventional draws",
      "VarCorr exposes draw-wise sdlog and sd_level",
      "VarCorr per-level covariance uses realized scales",
      "VarCorr summaries retain documented dimensions",
      "summary exposes sdlog hyperparameters"
    ),
    max_abs_error = c(
      if (extractor_ok) 0 else Inf,
      max_extractor_error,
      max_scale_error,
      max_cov_error,
      if (summary_shape_ok) 0 else Inf,
      if (summary_sdlog_ok) 0 else Inf
    ),
    tolerance = c(
      0, invariant_tolerance, invariant_tolerance,
      invariant_tolerance, 0, 0
    ),
    stringsAsFactors = FALSE
  )

  if (!case$student) {
    newdata <- case$data[seq_len(3L), , drop = FALSE]
    newdata$g <- factor(sprintf("new-g%02d", seq_len(nrow(newdata))))
    set.seed(case$seed + 2000L)
    pred <- posterior_linpred(
      fit, newdata = newdata, allow_new_levels = TRUE,
      sample_new_levels = "gaussian",
      draw_ids = seq_len(min(40L, ndraws))
    )
    prediction_ok <- identical(
      dim(pred), c(min(40L, ndraws), nrow(newdata))
    ) && all(is.finite(pred))
    checks <- rbind(
      checks,
      data.frame(
        case = case$name,
        check = "new Gaussian levels draw finite hierarchy scales/effects",
        max_abs_error = if (prediction_ok) 0 else Inf,
        tolerance = 0,
        stringsAsFactors = FALSE
      )
    )
  }
  checks$pass <- checks$max_abs_error <= checks$tolerance
  checks
}

reference_invariants <- function(fit, case, sdata, canonical) {
  draws <- fit$draws(format = "draws_array")
  coefs <- coefficient_names(case)
  levels_g <- levels(case$data$g)
  M <- length(coefs)
  J <- length(levels_g)
  max_scale_error <- 0
  max_finite_error <- 0
  max_predictor_error <- 0

  for (k in seq_len(M)) {
    baseline_sd <- canonical[[paste0("sd:", coefs[k])]]
    sdlog <- canonical[[paste0("sdlog:", coefs[k])]]
    b <- canonical[[paste0("b:", coefs[k])]]
    for (j in seq_len(J)) {
      z <- draw_matrix(draws, sprintf("z_scale[%d,%d]", k, j))
      expected_scale <- baseline_sd * exp(sdlog * z)
      saved_scale <- canonical[[
        sprintf("sd_level:%s,%s", levels_g[j], coefs[k])
      ]]
      max_scale_error <- max(max_scale_error, abs(expected_scale - saved_scale))
      finite <- b + canonical[[sprintf("r:%s,%s", levels_g[j], coefs[k])]]
      saved_finite <- canonical[[
        sprintf("b+r:%s,%s", levels_g[j], coefs[k])
      ]]
      max_finite_error <- max(max_finite_error, abs(finite - saved_finite))
    }
  }

  selected_obs <- unique(round(seq(1, nrow(case$data), length.out = 6L)))
  for (n in selected_obs) {
    group_n <- as.integer(case$data$g[n])
    eta <- matrix(
      0,
      nrow(canonical[["b:Intercept"]]),
      ncol(canonical[["b:Intercept"]])
    )
    for (k in seq_len(M)) {
      eta <- eta + sdata$X[n, k] * canonical[[
        sprintf("b+r:%s,%s", levels_g[group_n], coefs[k])
      ]]
    }
    max_predictor_error <- max(
      max_predictor_error,
      abs(eta - canonical[[sprintf("eta:observation[%d]", n)]])
    )
  }

  out <- data.frame(
    case = case$name,
    check = c(
      "reference sd_level hierarchy",
      "reference finite coefficient identity",
      "reference centered-intercept predictor"
    ),
    max_abs_error = c(
      max_scale_error, max_finite_error, max_predictor_error
    ),
    tolerance = invariant_tolerance,
    stringsAsFactors = FALSE
  )
  out$pass <- out$max_abs_error <= out$tolerance
  out
}

quality_from_quantities <- function(quantities, sampler_counts, case_name,
                                    parameterization) {
  summaries <- lapply(quantities, quantity_summary)
  rhats <- vapply(summaries, `[[`, numeric(1), "rhat")
  bulk <- vapply(summaries, `[[`, numeric(1), "ess_bulk")
  tail <- vapply(summaries, `[[`, numeric(1), "ess_tail")
  data.frame(
    case = case_name,
    parameterization = parameterization,
    max_rhat = max(rhats, na.rm = TRUE),
    min_bulk_ess = min(bulk, na.rm = TRUE),
    min_tail_ess = min(tail, na.rm = TRUE),
    divergences = sampler_counts[["divergences"]],
    max_treedepth_hits = sampler_counts[["max_treedepth_hits"]],
    pass = max(rhats, na.rm = TRUE) <= max_rhat &&
      min(bulk, na.rm = TRUE) >= min_bulk_ess &&
      min(tail, na.rm = TRUE) >= min_tail_ess &&
      sampler_counts[["divergences"]] <= max_divergences &&
      sampler_counts[["max_treedepth_hits"]] <= max_treedepth_hits,
    stringsAsFactors = FALSE
  )
}

brms_sampler_counts <- function(fit) {
  np <- brms::nuts_params(fit)
  c(
    divergences = sum(np$Value[np$Parameter == "divergent__"]),
    max_treedepth_hits = sum(
      np$Value[np$Parameter == "treedepth__"] >= max_treedepth
    )
  )
}

reference_sampler_counts <- function(fit) {
  diagnostics <- fit$sampler_diagnostics(format = "draws_array")
  c(
    divergences = sum(draw_matrix(diagnostics, "divergent__")),
    max_treedepth_hits = sum(
      draw_matrix(diagnostics, "treedepth__") >= max_treedepth
    )
  )
}

run_case <- function(case) {
  sdata <- make_standata(
    case$formula, data = case$data, family = gaussian(), prior = case$prior
  )
  s2z_fit <- sample_brms(case)
  reference_fit <- sample_reference(case, sdata)
  s2z <- brms_quantities(s2z_fit, case, sdata)
  reference <- reference_quantities(reference_fit, case, sdata)
  list(
    comparison = compare_quantities(reference, s2z, case$name),
    invariants = rbind(
      s2z_invariants(s2z_fit, case, sdata, s2z),
      s2z_public_api_invariants(s2z_fit, case, s2z),
      reference_invariants(reference_fit, case, sdata, reference)
    ),
    quality = rbind(
      quality_from_quantities(
        reference, reference_sampler_counts(reference_fit), case$name,
        "conventional"
      ),
      quality_from_quantities(
        s2z, brms_sampler_counts(s2z_fit), case$name, "s2z"
      )
    ),
    s2z_fit = s2z_fit,
    reference_fit = reference_fit
  )
}

results <- lapply(requested_cases, function(name) run_case(make_case(name)))
comparison_results <- do.call(rbind, lapply(results, `[[`, "comparison"))
comparison_results <- comparison_results[
  order(comparison_results$z_score, decreasing = TRUE),
]
invariant_results <- do.call(rbind, lapply(results, `[[`, "invariants"))
quality_results <- do.call(rbind, lapply(results, `[[`, "quality"))

cat("\nMCSE- and margin-aware posterior comparisons (largest 30 z-scores)\n")
print(utils::head(comparison_results, 30L), row.names = FALSE, digits = 4)
cat("\nExact hierarchy and coordinate invariants\n")
print(invariant_results, row.names = FALSE, digits = 5)
cat("\nSampling quality\n")
print(quality_results, row.names = FALSE, digits = 5)

if (nzchar(output_dir)) {
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  utils::write.csv(
    comparison_results,
    file.path(output_dir, "s2z-varying-scale-equivalence.csv"),
    row.names = FALSE
  )
  utils::write.csv(
    invariant_results,
    file.path(output_dir, "s2z-varying-scale-invariants.csv"),
    row.names = FALSE
  )
  utils::write.csv(
    quality_results,
    file.path(output_dir, "s2z-varying-scale-quality.csv"),
    row.names = FALSE
  )
  utils::write.csv(
    configuration,
    file.path(output_dir, "s2z-varying-scale-settings.csv"),
    row.names = FALSE
  )
  cat("Full outcomes written to ", normalizePath(output_dir), "\n", sep = "")
}

failed_comparisons <- subset(comparison_results, !pass)
failed_invariants <- subset(invariant_results, !pass)
failed_quality <- subset(quality_results, !pass)
if (nrow(failed_comparisons) || nrow(failed_invariants) ||
    nrow(failed_quality)) {
  stop(
    "Group-varying-scale validation failed: ",
    nrow(failed_comparisons), " posterior comparisons, ",
    nrow(failed_invariants), " exact invariants, and ",
    nrow(failed_quality), " sampler checks failed.",
    call. = FALSE
  )
}

cat(
  "\nPASS: the actual brms S2Z fits and exact conventional varying-scale ",
  "hierarchies agree for means, SDs, and quantiles within propagated MCSE ",
  "and prespecified margins; scale, b+r, and predictor identities hold ",
  "draw by draw; all sampler checks pass.\n",
  sep = ""
)
