name: R-CMD-check (Fork-only)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', rtools: '42'}
          - {os: ubuntu-22.04, r: 'devel',   rtools: ''}
          - {os: ubuntu-22.04, r: 'release', rtools: ''}
          - {os: ubuntu-22.04, r: 'oldrel-1', rtools: ''}

    env:
      R_KEEP_PKG_SOURCE: yes
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          rtools-version: ${{ matrix.config.rtools }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: NA
          extra-packages: |
            R.rsp
            knitr
            rcmdcheck
            rmarkdown
            lme4
            mice
            BH
            MCMCglmm
            ape
            stan-dev/cmdstanr
            RcppEigen
            testthat
            emmeans
            projpred
            priorsense
            RWiener
            rtdists
            extraDistr
            spdep
            mnormt
            splines2
            arm
            statmod
            diffobj
            betareg

      - name: Build CmdStan
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan(cores = parallel::detectCores())
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual", "--no-build-vignettes")'
          args: 'c("--no-manual", "--as-cran", "--ignore-vignettes")'
